Version: "2018-07-04"

Name: ReadMessages

Description: LambdaSharp demo app - read messages from Dynamo

Parameters:

  - Name: MessageTable
    Description: Imported DynamoDb table for storing received messages
    Import: Messages/dynamo
    Resource:
      Type: AWS::DynamoDB::Table
      Allow: ReadWrite

Functions:

  - Name: ReadTable
    Description: Show messages in a DynamoDB table
    Memory: 128
    Timeout: 30
    Sources:
      - Api: GET:/
